//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFClient.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a message to send to chat..
        /// </summary>
        internal static string ChatInputPlaceholder {
            get {
                return ResourceManager.GetString("ChatInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an identity for this provider&apos;s platform..
        /// </summary>
        internal static string Error_NewProviderEnterIdentity {
            get {
                return ResourceManager.GetString("Error_NewProviderEnterIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a chat density..
        /// </summary>
        internal static string Error_NewProviderSelectDensity {
            get {
                return ResourceManager.GetString("Error_NewProviderSelectDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a provider..
        /// </summary>
        internal static string Error_NewProviderSelectProvider {
            get {
                return ResourceManager.GetString("Error_NewProviderSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string ExitCommand {
            get {
                return ResourceManager.GetString("ExitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your identity on the chosen platform..
        /// </summary>
        internal static string IdentityInputPlaceholder {
            get {
                return ResourceManager.GetString("IdentityInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Moderation Bot.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MenuLanguageEN {
            get {
                return ResourceManager.GetString("MenuLanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string MenuLanguageJP {
            get {
                return ResourceManager.GetString("MenuLanguageJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start _New Provider.
        /// </summary>
        internal static string NewProviderCommand {
            get {
                return ResourceManager.GetString("NewProviderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Provider.
        /// </summary>
        internal static string NewProviderDialog {
            get {
                return ResourceManager.GetString("NewProviderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a live Niconico stream chat.
        ///
        ///A full implementation would require valid login credentials for an appropriately-permissioned account to post comments or perform moderation actions. These credentials could be collected here..
        /// </summary>
        internal static string NiconicoDesc {
            get {
                return ResourceManager.GetString("NiconicoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニコニコ.
        /// </summary>
        internal static string NicoNicoTitle {
            get {
                return ResourceManager.GetString("NicoNicoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Identity.
        /// </summary>
        internal static string PlatformIdentityLabel {
            get {
                return ResourceManager.GetString("PlatformIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a live Twitch stream chat.
        ///
        ///A full implementation would require collecting an OAuth token, which could be done here..
        /// </summary>
        internal static string TwitchDesc {
            get {
                return ResourceManager.GetString("TwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        internal static string TwitchTitle {
            get {
                return ResourceManager.GetString("TwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a chat density:.
        /// </summary>
        internal static string TwitchVODDensity {
            get {
                return ResourceManager.GetString("TwitchVODDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (200 messages per minute).
        /// </summary>
        internal static string TwitchVODDensityHigh {
            get {
                return ResourceManager.GetString("TwitchVODDensityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (30 messages per minute).
        /// </summary>
        internal static string TwitchVODDensityLow {
            get {
                return ResourceManager.GetString("TwitchVODDensityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (90 messages per minute).
        /// </summary>
        internal static string TwitchVODDensityMedium {
            get {
                return ResourceManager.GetString("TwitchVODDensityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay a provided Twitch VOD chat log in real time, with different densities to demonstrate the bot&apos;s abilities..
        /// </summary>
        internal static string TwitchVODDesc {
            get {
                return ResourceManager.GetString("TwitchVODDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch
        ///VOD Chat Replay.
        /// </summary>
        internal static string TwitchVODTitle {
            get {
                return ResourceManager.GetString("TwitchVODTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a live YouTube stream chat.
        ///
        ///A full implementation would require Google OAuth and permissions granting from the YouTube account, which could be triggered here..
        /// </summary>
        internal static string YoutubeDesc {
            get {
                return ResourceManager.GetString("YoutubeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        internal static string YoutubeTitle {
            get {
                return ResourceManager.GetString("YoutubeTitle", resourceCulture);
            }
        }
    }
}
